#!/usr/bin/env python3
"""
API Key Setup Wizard for ASCII-Generator.
Securely stores API keys in a LOCAL .env file (never uploaded to git).
"""
import os
import sys
from pathlib import Path

def setup_api_keys():
    """Interactive wizard to set up API keys securely."""
    print("=" * 70)
    print("  ASCII-Generator API Key Setup")
    print("=" * 70)
    print()
    print("This wizard will help you set up your API keys securely.")
    print("Your keys will be stored LOCALLY in a .env file and never shared.")
    print()

    # Get project directory
    project_dir = Path(__file__).parent.absolute()
    env_file = project_dir / ".env"

    # Check if .env exists
    env_exists = env_file.exists()
    if env_exists:
        print(f"⚠️  Found existing .env file at: {env_file}")
        response = input("Do you want to UPDATE it? (y/n): ").strip().lower()
        if response != 'y':
            print("Setup cancelled.")
            return
        print()

    # Load existing values if any
    existing_env = {}
    if env_exists:
        with open(env_file, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    existing_env[key.strip()] = value.strip()

    # Collect API keys
    print("=" * 70)
    print("  API Key Configuration")
    print("=" * 70)
    print()

    # Groq API Key
    print("1️⃣  Groq API Key (moonshotai/kimi-k2-instruct)")
    print("   Get your free key at: https://console.groq.com/keys")
    print()
    current_groq = existing_env.get('GROQ_API_KEY', '')
    if current_groq:
        print(f"   Current: {current_groq[:10]}...{current_groq[-4:]}")
        groq_key = input("   New Groq API key (or press Enter to keep current): ").strip()
        if not groq_key:
            groq_key = current_groq
    else:
        groq_key = input("   Enter Groq API key (or press Enter to skip): ").strip()

    print()

    # Gemini API Key
    print("2️⃣  Google Gemini API Key (optional)")
    print("   Get your free key at: https://makersuite.google.com/app/apikey")
    print()
    current_gemini = existing_env.get('GEMINI_API_KEY', '')
    if current_gemini:
        print(f"   Current: {current_gemini[:10]}...{current_gemini[-4:]}")
        gemini_key = input("   New Gemini API key (or press Enter to keep current): ").strip()
        if not gemini_key:
            gemini_key = current_gemini
    else:
        gemini_key = input("   Enter Gemini API key (or press Enter to skip): ").strip()

    print()

    # Model selection
    print("3️⃣  Groq Model (optional - default: moonshotai/kimi-k2-instruct-0905)")
    current_model = existing_env.get('GROQ_MODEL', 'moonshotai/kimi-k2-instruct-0905')
    print(f"   Current: {current_model}")
    groq_model = input("   Enter Groq model (or press Enter to use default): ").strip()
    if not groq_model:
        groq_model = current_model

    print()
    print("=" * 70)

    # Validate
    if not groq_key and not gemini_key:
        print("⚠️  No API keys provided. You need at least one to use ASCII-Generator.")
        response = input("Continue anyway? (y/n): ").strip().lower()
        if response != 'y':
            print("Setup cancelled.")
            return

    # Write .env file
    print()
    print(f"Writing configuration to: {env_file}")

    with open(env_file, 'w') as f:
        f.write("# ASCII-Generator API Configuration\n")
        f.write("# This file is LOCAL and should never be committed to git!\n")
        f.write("#\n")
        f.write("# Generated by setup_keys.py\n")
        f.write("#\n\n")

        if groq_key:
            f.write("# Groq API Configuration\n")
            f.write(f"GROQ_API_KEY={groq_key}\n")
            f.write(f"GROQ_MODEL={groq_model}\n")
            f.write("\n")

        if gemini_key:
            f.write("# Google Gemini API Configuration\n")
            f.write(f"GEMINI_API_KEY={gemini_key}\n")
            f.write("\n")

        # Other settings
        f.write("# Optional Settings\n")
        f.write(f"DEFAULT_TIMEOUT={existing_env.get('DEFAULT_TIMEOUT', '30')}\n")

    # Set permissions (read/write for owner only)
    os.chmod(env_file, 0o600)

    print()
    print("✅ Configuration saved successfully!")
    print()
    print("=" * 70)
    print("  Security Information")
    print("=" * 70)
    print()
    print(f"📁 Your API keys are stored in: {env_file}")
    print("🔒 File permissions: Read/Write for you ONLY")
    print("🚫 This file is .gitignored and will NOT be uploaded to GitHub")
    print("⚠️  NEVER share your .env file or commit it to version control!")
    print()
    print("=" * 70)
    print("  Next Steps")
    print("=" * 70)
    print()
    print("1. Test your setup:")
    print("   $ ascii check")
    print()
    print("2. Generate your first ASCII art:")
    print("   $ ascii art \"a cat\"")
    print()
    print("3. Try live mode:")
    print("   $ ascii art \"a dragon\" --live --provider groq")
    print()
    print("Enjoy! 🎨")
    print()

if __name__ == "__main__":
    try:
        setup_api_keys()
    except KeyboardInterrupt:
        print("\n\nSetup cancelled by user.")
        sys.exit(1)
    except Exception as e:
        print(f"\n\n❌ Error: {e}")
        sys.exit(1)
